### ISSUE TITLE
Jakie są cele naszych projektów?

### ISSUE THREAD

**Issue by pdulak** [dataworkshop/dw-cracow-project-DO-NOT-USE#3]
Szukamy celu, kierunku w którym powinny podążać nasze projekty

**Comment by pjodko** [comment]
Czy możesz rozwinąć interpelację? ;) 
Projekty są zgrubnie opisane na wiki, ale jak rozumiem, pewnej informacji (w sumie, wielu) tam nie ma.
Może pytania pomocnicze, tak byśmy mogli się przygotować na rozmowę?

**Comment by pdulak** [comment]
Chodzi o znalezienie konkretnych celów do których dane projekty miały by dążyć. Pytania pomocnicze:
- co chcę uzyskać realizująć ten projekt? Jaki efekt społeczny, biznesowy?
- jaki problem chcę rozwiązać? Jakie dodatkowe problemy mogę przy okazji rozwiązać?
- dlaczego według mnie warto rozwiązać ten problem?

Mógłbym podać przykładowe odpowiedzi, ale nie chcę narzucać swojego kierunku i punktu widzenia :)
